### ISSUE TITLE
Input bam format discrepancy. Error when running subset_metatada.py

### ISSUE THREAD

**Issue by Eneritz** [p-CMRC-LAB/SCALPEL#1]
Hi Franz,
Great tool and congrats on the documentation.

I am running the pipeline with 10X human data. I already run the preprocessing.

nextflow run -resume SCALPEL/scalpel.nf --sequencing chromium --folder_in CR_outs/ --annot  gencode.v43.annotation.gtf  --ipdb refdata-gex-GRCh38-2020-A.polyA.track --quant_file preprocessing/quant.filtered

 The processing stops here:

    Convertion of bam files to bed files (1)
    bam2bed --all-reads --split --do-not-sort < chr1.ebam > temp_file
  
     Extract relevant metadata infos and sort for overlapping purposes (2)
     python3 SCALPEL/src/subset_metatada.py temp_file chr1.bed_

  The error is basically that 2 lines in the bam files have 14 fields instead of 15

    pandas.errors.ParserError: Error tokenizing data. C error: Expected 14 fields in line 9502722, saw 15

I looked the them tmp file from the ebam and indeed they have different of fields 

      chr1	93342414	93342505	VH00203:5:AAAJNVVM5:1:1607:23760:40377/1	255	-	16	91M	*	0	0	AACCTACTTTTCCTACATCATATACCACTACAAACTCTTTACAAACCTTATTAATAGAGCCACTCTAGACTACTTTATTTCCCCAAGCCATA	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CC;CCCCCCCCCCCCCCCCCCCCCCCCCCCC;C;CCCCCC	CB:Z:TCCACCATCCGCCTAT-1
      chr1	93342420	93342511	VH00203:5:AAAJNVVM5:1:2603:49721:15748/1	255	-	16	91M	*	0	0	CTTTTCCTGCATCACATACCACTACACCTCTTTACACACCTTATTAATAGAGCCACTCTAGACTACTTTATTTCCCCAAGCCATACAATGT	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	CB:Z:ACAAAGACATCAGCGC-1	UB:Z:TGAAGCAAATAG

Some are missing the UB:Z tag. 

Do you think that can be edited, allowing different number of fields, or is it a problem with my bam files?

Thanks!

E.

**Comment by Eneritz** [comment]
Hi again,
I have filtered the bam file before running the pipeline and now everything works perfect. :)

**Comment by Franzx7** [comment]
Dear @Eneritz ,
Thanks for your usage of Scalpel.

Effectively, Scalpel read the bam file and select only the Barcode and UMI tags for the downstream processes. 
A solution is to filter the bam file as you did to keep only the reads for which those tags are present.
